# Generated by Django 4.0.5 on 2022-09-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('random_weights_dict', models.JSONField(blank=True, null=True)),
                ('responses', models.ManyToManyField(blank=True, related_name='requests', to='baseapp.message')),
            ],
        ),
    ]
