# Generated by Django 4.0.5 on 2022-09-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_alter_message_random_weights_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='random_weights_dict',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
